### ISSUE TITLE
WSDL HW není hotov

### ISSUE THREAD

**Issue by jakubklimek** [BakhtinArtem/NSWI145#1]
WSDL domácí úkol není hotov - cílem bylo napsat použitelné WSDL. Vy jste evidentně použil WSDL generované vaší JAVA implementací, a chybí tam např. XML schéma.

**Comment by BakhtinArtem** [comment]
Dneska opravím

**Comment by BakhtinArtem** [comment]
Upraveno

**Comment by jakubklimek** [comment]
Nyní jsou ty wsdl soubory skoro prázdné.

**Comment by BakhtinArtem** [comment]
> Nyní jsou ty wsdl soubory skoro prázdné.

jj, nevím proč, commitnulo se mi poluprazdná xmlka. už jsem to opravil
