### ISSUE TITLE
HW9: Incorrect usage of classes and properties

### ISSUE THREAD

**Issue by jakubklimek** [BakhtinArtem/NSWI145#3]
In your diagram, you use some properties as classes (e.g. dcterms:license, schema:customer, schema:employee), see [the slide with common mistakes](https://docs.google.com/presentation/d/1taDTuEOPkCa7roLYtHFgrbz8u1bIbnF0sAGj9tG1lmo/edit#slide=id.g22f9981f5de_0_16). This can be spotted right away, because in the Web vocabularies there is a convention that class IRIs start with capital letter after prefix, properties with lowercase letter after prefix.

In addition

1. the generalization edge needs to have an empty triangle at the end
2. your ex: prefix definition is missing a slash at the end

**Comment by BakhtinArtem** [comment]
1. FIXED
2. FIXED
